name: Feature Request
description: I will not add multiple key supports (such as 6K, 9K, etc). DO NOT REQUEST STAGE EDITOR! I MAY OR MAY NOT ADD IT IN! IF YOU REALLY NEED IT JUST USE OS ENGINE!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Stage Editor, 6K+ support, and winning icons.
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
