name: Missing Documentation
description: Ask for documentation if something is missing. (PE Wiki - https://github.com/ShadowMario/FNF-PsychEngine/wiki)
labels: [documentation]
body:
  - type: textarea
    attributes:
      label: What needs to be documented?
      description: 'For example: "There is no page explaining how to create an Achievement!"'
    validations:
      required: true